- name: Docker to all vms
  hosts: cluster
  become: yes
  roles:
    - docker

- name: Prerequisite the master
  hosts: master
  become: yes
  gather_facts: false
  roles:
    - kubernetes-master
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join to cluster
  hosts: nodes
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt