apiVersion: v1
kind: Pod
metadata:
  name: secret-testing-pod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: secret-data-name
      mountPath: "/etc/foo"
      readOnly: true
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secret-data
            key: username
            optional: false # same as default; "mysecret" must exist
                            # and include a key named "username"
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-data
            key: password
            optional: false # same as default; "mysecret" must exist
                            # and include a key named "password"
  volumes:
  - name: secret-data-name
    secret:
      secretName: secret-data
      optional: false