---
# tasks file for cri-dockerd
- name: Checkout from from ri-dockerd github
  git:
    repo: 'https://github.com/Mirantis/cri-dockerd.git'
    dest: cri-dockerd

- name: Install go
  apt:
    pkg:
      - golang-go
    state: latest
    update_cache: true

- name: Create a directory bin
  file:
    path: cri-dockerd/bin
    state: directory
    mode: '0755'

- name: Go build
  shell: go build -o bin/cri-dockerd >> go_cri_dockerd_builded.log
  args:
    chdir: $HOME
    creates: go_cri_dockerd_builded.log

- name: Create a directory if it does not exist
  file:
    path: /usr/local/bin
    state: directory
    mode: '0744'

- name: Install cri-dockerd
  shell: install -o root -g root -m 0755 cri-dockerd/bin/cri-dockerd /usr/local/bin/cri-dockerd
  args:
    chdir: $HOME
    creates: go_cri_dockerd_builded.log

- name: Copy cri-dockerd files to /etc/systemd
  copy:
    src: cri-dockerd/packaging/systemd/
    remote_src: true
    dest: /etc/systemd/system
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Replace data in files
  shell: sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
  args:
    chdir: $HOME
    creates: sed_completed.log

- name: Daemon reload
  systemd:
    daemon_reload: yes

- name: Reload service httpd, in all cases
  systemd:
    name: "{{ item }}"
    state: reloaded
  loop:
    - cri-docker.service
    - cri-docker.socket