---
# tasks file for kubernetes-master
- name: Initialize the cluster
  shell: kubeadm init --kubernetes-version=v1.22.0 --config /home/{{ ansible_user }}/ansible/kubeadm-config.yml >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.log

- name: Sleep for 20 seconds
  wait_for:
    timeout: 20

- name: Create a directory if it does not exist
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: install Pod network 
  shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt