---
# tasks file for kubernetes-master
- name: Add a line to sysctl.conf
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
    create: yes
  with_items:      
    - net.bridge.bridge-nf-call-iptables = 1
    - net.ipv4.ip_forward = 1
    - net.bridge.bridge-nf-call-ip6tables = 1
    - vm.overcommit_memory = 1
    - net.ipv4.ip_nonlocal_bind = 1

- name: Initialize the cluster
  shell: kubeadm init --config /home/{{ ansible_user }}/ansible/kubeadm-config.yml >> cluster_initialized.txt
  args:
    chdir: /home/{{ ansible_user }}
    creates: cluster_initialized.log

- name: Sleep for 20 seconds
  wait_for:
    timeout: 20

- name: Create a directory if it does not exist
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: install Pod network 
  shell: kubectl apply --kubeconfig /home/{{ ansible_user }}/.kube/config -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt